systemd.user.services.rs-reminder = {
  enable = true;
  after = [ "network.target" ];
  wantedBy = [ "multi-user.target" ];
  description = "RS Reminder Bot";
  serviceConfig = {
      Type = "simple";
      Restart = "always";
      RestartSec = "10s";
      Environment = ["DISCORD_TOKEN=<token>" "DISCORD_CHANNEL_ID=<id>"];
      ExecStart = ''/home/mac/rs-reminder-bot/target/release/rs-reminder-bot'';
      BindReadOnlyPaths = ["/home/mac/rs-reminder-bot/target/release"];
      # Hardening
      ProtectHome = "tmpfs";
      CapabilityBoundingSet = "";
      RestrictNamespaces = true;
      NoNewPrivileges = true;
      PrivateTmp = true;
      ProtectSystem = "strict";
      PrivateDevices = true;
      PrivateUsers = true;
      ProtectClock = true;
      ProtectControlGroups = true;
      ProtectKernelLogs = true;
      ProtectKernelModules = true;
      ProtectKernelTunables = true;
      ProtectProc = "invisible";
      ProcSubset = "pid";
      RestrictSUIDSGID = true;
      SystemCallArchitectures = "native";
      RestrictRealtime = true;
      LockPersonality = true;
      RemoveIPC = true;
      MemoryDenyWriteExecute = true;
      UMask = "077";
      ProtectHostname = true;
      SystemCallFilter = "@system-service";
      DevicePolicy = "strict";
      DeviceAllow = ["/dev/null rw" "/dev/random r" "/dev/urandom r"];
  };
};
